export const FETCH_PERSONAL_DATA_SUCCESS = '@profile/FETCH_PERSONAL_DATA_SUCCESS_SUCCESS'
export const FETCH_PERSONAL_DATA_ERROR = '@profile/FETCH_PERSONAL_DATA_ERROR'

export const CHANGE_PASSWORD_SUCCESS = '@profile/CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_ERROR = '@profile/CHANGE_PASSWORD_ERROR'
export const RESET_CHANGE_PASSWORD_STATUS = '@profile/RESET_CHANGE_PASSWORD_STATUS'

export const AUTH_INIT = '@auth/AUTH_INIT'
export const AUTH_SUCCESS = '@auth/AUTH_SUCCESS'
export const AUTH_ERROR = '@auth/AUTH_ERROR'
export const AUTH_RESET = '@auth/AUTH_RESET'
export const AUTH_LOGOUT_SUCCESS = '@auth/LOGOUT_SUCCESS'

export const FETCH_CHATS_SUCCESS = '@chats/FETCH_CHATS_SUCCESS'
export const FETCH_CHATS_ERROR = '@chats/FETCH_CHATS_ERROR'
export const CREATE_CHAT_SUCCESS = '@chats/CREATE_CHAT_SUCCESS'
